"""8

Revision ID: 83804c36239f
Revises: 534007fa3009
Create Date: 2025-05-06 01:43:17.968888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83804c36239f'
down_revision: Union[str, None] = '534007fa3009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_cover_image_id_fkey', 'articles', type_='foreignkey')
    op.drop_column('articles', 'cover_image_id')
    op.add_column('images', sa.Column('type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'type')
    op.add_column('articles', sa.Column('cover_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('articles_cover_image_id_fkey', 'articles', 'images', ['cover_image_id'], ['id'])
    # ### end Alembic commands ###
