"""7

Revision ID: 534007fa3009
Revises: efc4393284ac
Create Date: 2025-05-06 00:15:16.762696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534007fa3009'
down_revision: Union[str, None] = 'efc4393284ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.drop_constraint('articles_image_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'images', ['cover_image_id'], ['id'])
    op.drop_column('articles', 'image_id')
    op.add_column('images', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'article_id')
    op.add_column('articles', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_image_id_fkey', 'articles', 'images', ['image_id'], ['id'])
    op.drop_column('articles', 'cover_image_id')
    # ### end Alembic commands ###
