"""3

Revision ID: 5ae67a76b864
Revises: f7cc925afa3d
Create Date: 2025-05-05 15:02:11.345795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae67a76b864'
down_revision: Union[str, None] = 'f7cc925afa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_articles', sa.Column('key', sa.String(length=512), nullable=False))
    op.drop_column('deleted_articles', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_articles', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('deleted_articles', 'key')
    # ### end Alembic commands ###
