"""13

Revision ID: e2acdc52480a
Revises: 6de5e70c66cb
Create Date: 2025-05-11 05:59:59.856926

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e2acdc52480a'
down_revision: Union[str, None] = '6de5e70c66cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
