"""6

Revision ID: efc4393284ac
Revises: 8a08cdb809af
Create Date: 2025-05-05 23:29:15.518180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc4393284ac'
down_revision: Union[str, None] = '8a08cdb809af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deleted_articles')
    op.add_column('articles', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'images', ['image_id'], ['id'])
    op.drop_column('articles', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'image_id')
    op.create_table('deleted_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='deleted_articles_pkey'),
    sa.UniqueConstraint('article_id', name='deleted_articles_article_id_key')
    )
    op.drop_table('images')
    # ### end Alembic commands ###
