"""2

Revision ID: f7cc925afa3d
Revises: e66b98a425ae
Create Date: 2025-05-03 21:14:55.567995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cc925afa3d'
down_revision: Union[str, None] = 'e66b98a425ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('key', sa.String(length=512), nullable=False))
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('articles', 'key')
    # ### end Alembic commands ###
